### ISSUE TITLE
unable to loader share library ./x11.os

### ISSUE THREAD

**Issue by xiaoxinxing12** [lucassklp/Desktop.Robot#15]
ubuntu 18.04

unable to loader share library ./x11.os,  consider setting the LD_DEBUG environment variable

**Comment by Apfelwurm** [comment]
We sadly have the same problem on linux with the x11.os as well as on osx with the osx.os:
https://github.com/MakroBoard/MakroBoard/issues/40
https://github.com/MakroBoard/MakroBoard/issues/46

**Comment by lucassklp** [comment]
Sorry for delay to fix this, but now it's fixed. 
I had to test it directly on main branch, in order to the package be published on nuget. I tested it on my mac and linux, worked fine!

The commit that fixed this issue: https://github.com/lucassklp/Desktop.Robot/commit/6fa8d2b281c4e9c1de6d131440ee395a5947f947

Now i'm publishing as stable version (instead of alpha) in this MR:
https://github.com/lucassklp/Desktop.Robot/pull/17
