### ISSUE TITLE
Key.Press not working in macos (ARM)

### ISSUE THREAD

**Issue by AnnikaJoo** [lucassklp/Desktop.Robot#36]
Hello, 
In my program I use the command KeyDown(Key.Shift). Everything works fine under Windows. I have now switched to Macos (ARM) and the command throws an exception. 

Error Message:
`System.DllNotFoundException: Unable to load shared library './osx.os' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(./osx.os, 0x0001): tried: './osx.os' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS./osx.os' (no such file), '/usr/lib/./osx.os' (no such file, not in dyld cache), './osx.os' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')),`

Thank u for the help.

**Comment by lucassklp** [comment]
Thank you! Now I understood the problem, this is related to the architecture. I'll take a look and see how can I work with different architectures and provide one for this case

**Comment by AnnikaJoo** [comment]
Hi @lucassklp , is there any news or progress already? :)

**Comment by lucassklp** [comment]
Hello @AnnikaJoo . Unfortunately I cannot develop it, because I am unable to test things, since I don't have any MacOS with ARM architecture. I'd be glad if you could do this. Try to compile https://github.com/lucassklp/Desktop.Robot/blob/main/Desktop.Robot/Source/osx/main.mm in your local machine and tell me if it worked
