### ISSUE TITLE
Question regarding multiple monitors

### ISSUE THREAD

**Issue by vgb1993** [lucassklp/Desktop.Robot#4]
Hy there, I've just stumbled upon your project. Very interesting indeed!

I was wondering, how hard would it be to support multiple monitors? Are you currently working on this?

Cheers :)

**Comment by lucassklp** [comment]
Hi there!

As this library needs to be multiplatform, I am using S.O APIs to build it.
In order to implement multiple monitors feature I'll need to study how does the cursor coordinate system works on each S.O and I think that's the hardest part.

Once it's done, I have to think how I could create a single interface to be compatible with these differents APIs. But that's easy
